DocumentStorage.WebUI/Controllers/NavController.cs
using DocumentStorage.WebUI.Models;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DocumentStorage.WebUI.Controllers
{
    public class NavController : Controller
    {
        public PartialViewResult Menu()
        {
            

            NavMenuViewModel model = new NavMenuViewModel() {
                ListFilterInfo = (ListFilterInfo)Session["FilterInfo"] ?? new ListFilterInfo()
            };

            bool isAuthorised = Request.IsAuthenticated;
            ViewBag.isAuthorized = isAuthorised;

            if (isAuthorised)
            {
                string cookieName = FormsAuthentication.FormsCookieName;
                HttpCookie authCookie = HttpContext.Request.Cookies[cookieName];
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);
                string UserName = ticket.Name;
                ViewBag.UserName = UserName;
            }
            

            

            return PartialView(model);
        }

    }
}

DocumentStorage.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Хранилище документов</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>

    @{ Html.RenderAction("Menu", "Nav"); }

    <div class="container">

        @RenderBody()

    </div>




    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
   </body>
</html>