DocumentStorage.WebUI/Controllers/DocumentController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentStorage.Domain.Abstract;
using DocumentStorage.Domain.Entities;
using DocumentStorage.WebUI.Models;
using DocumentStorage.WebUI.Models.Helpers;
using System.Web.Security;
using System.Collections.Generic;

namespace DocumentStorage.WebUI.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private IDocumentsRepository repository;
        public int PageSize = 5;
        private string UserName { get {
            string cookieName = FormsAuthentication.FormsCookieName;
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieName];
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);
            string User = ticket.Name;

            return User;
        } }

        public DocumentController(IDocumentsRepository documentsRepository)
        {
            this.repository = documentsRepository;
        }

        

        public ViewResult List(DocumentsListViewModel model, NavMenuViewModel menu, int? SubmitOrder, int? SubmitFilter, int page = 1)
        {
            if (SubmitOrder == null && Session["OrderInfo"] == null)
            {
                model.OrderInfo = new OrderInfo();
            }
            else if (SubmitOrder == null && Session["OrderInfo"] != null)
            {
                model.OrderInfo = (OrderInfo)Session["OrderInfo"];
            }
            else
            {
                Session["OrderInfo"] = model.OrderInfo;
            }

            if (SubmitFilter != null)
                Session["FilterInfo"] = menu.ListFilterInfo;

            model.FilterInfo = (ListFilterInfo)Session["FilterInfo"] ?? new ListFilterInfo();

            model.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize
            };
            
            IEnumerable<Document> documents = DocumentsListGeneratorHelper.GetDocumentsList(model, repository);
            model.PagingInfo.TotalItems = documents.Count();
            model.Documents = documents
                .Skip((model.PagingInfo.CurrentPage - 1) * model.PagingInfo.ItemsPerPage)
                .Take(model.PagingInfo.ItemsPerPage);


            return View(model);
        }

        
        public ViewResult Create()
        {
            return View();
        }


        [HttpPost]
        public ViewResult Create(DocumentCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string fileFullName = model.Name + ".docx";
                string relativePath = DirectoryPathHelper.GetRelativePath(fileFullName, Server.MapPath);
                string absolutePath = Server.MapPath(relativePath);

                CreateDocumentHelper.Create(absolutePath, model.Content);

                 DocxToPdfHelper.Convert(absolutePath);
                

                Author author = repository.Authors.Single(a => a.Login == UserName);
                Document doc = new Document() { Author = author, Date = DateTime.Now, Name = model.Name, Url = relativePath };
                repository.AddDocument(doc);

                return View("Message", doc);
            }
            else
            {
                return View();
            }
            
        }


        public ViewResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Upload(DocumentUploadViewModel model)
        {
            
            if (ModelState.IsValid)
            {

                string fileFullName = System.IO.Path.GetFileName(model.uploadFile.FileName);
                string relativePath = DirectoryPathHelper.GetRelativePath(fileFullName, Server.MapPath);
                string absolutePath = Server.MapPath(relativePath);

                model.uploadFile.SaveAs(absolutePath);

                DocxToPdfHelper.Convert(absolutePath);

                Author author = repository.Authors.Single(a => a.Login == UserName);
                Document doc = new Document() { Author = author, Date = DateTime.Now, Name = model.Name, Url = relativePath };
                repository.AddDocument(doc);

                return View("Message", doc);
            }
            else
            {
                return View();
            }
            
        }



        public ActionResult Open(int documentID)
        {
            Document doc = repository.Documents.Single(d => d.DocumentID == documentID);

            return File(Server.MapPath(doc.Url + ".pdf"), "application/pdf");
        }


        public ActionResult Download(int documentID)
        {
            Document doc = repository.Documents.Single(d => d.DocumentID == documentID);

            string fileExtention = doc.Url.Substring(doc.Url.LastIndexOf('.')).ToLower();
            string mimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            
            return File(Server.MapPath(doc.Url),  mimeType, doc.Name + fileExtention);
        }

        public ViewResult Message(Document doc)
        {
            return View(doc);
        }


    }
}

DocumentStorage.WebUI/Controllers/NavController.cs
using DocumentStorage.WebUI.Models;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DocumentStorage.WebUI.Controllers
{
    public class NavController : Controller
    {
        public PartialViewResult Menu()
        {
            

            NavMenuViewModel model = new NavMenuViewModel() {
                ListFilterInfo = (ListFilterInfo)Session["FilterInfo"] ?? new ListFilterInfo()
            };

            bool isAuthorised = Request.IsAuthenticated;
            ViewBag.isAuthorized = isAuthorised;

            if (isAuthorised)
            {
                string cookieName = FormsAuthentication.FormsCookieName;
                HttpCookie authCookie = HttpContext.Request.Cookies[cookieName];
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);
                string UserName = ticket.Name;
                ViewBag.UserName = UserName;
            }
            

            

            return PartialView(model);
        }

    }
}

DocumentStorage.WebUI/Views/Nav/Menu.cshtml
@model DocumentStorage.WebUI.Models.NavMenuViewModel


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ХРАНИЛИЩЕ ДОКУМЕНТОВ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    @if (ViewBag.isAuthorized) {  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                @Html.ActionLink("Домой", "", "", null, new { @class = "nav-link"})
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Новый документ
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                    @Html.ActionLink("Создать", "Create", "Document", null, new { @class = "dropdown-item" })
                    @Html.ActionLink("Загрузить с ПК", "Upload", "Document", null, new { @class = "dropdown-item" })
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Аккаунт: @ViewBag.UserName 
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                    @Html.ActionLink("Выход", "Logout", "Account", null, new { @class = "dropdown-item" })
                </div>
            </li>

        </ul>

        @{
            List<SelectListItem> dropDownItems = new List<SelectListItem>();
            foreach (var item in @Model.ListFilterInfo.SearchAmoungOptions)
            {
                dropDownItems.Add(new SelectListItem
                {
                    Text = item.Value,
                    Value = item.Key,
                    Selected = @Model.ListFilterInfo.SearchAmoung == item.Key
                });

            }
        }
        @using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-inline my-2 my-lg-0" }))
        {
            <label class="text-light m-1" for="searchFromSelect">Искать: </label>
            @Html.DropDownListFor(m => m.ListFilterInfo.SearchAmoung, dropDownItems, new { @class = "form-control mr-sm-2", @id = "searchFromSelect" })
            @Html.TextBoxFor(m => m.ListFilterInfo.SearchString, new { @class = "form-control mr-sm-2", @placeholder="Поиск" })            
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" name="SubmitFilter" value="1">Поиск</button>
        }
       
    </div>
    }
</nav>